name: Bug Report
description: Report a reproducible bug in LOQ Nova
title: "[Bug] "
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of LOQ Nova are you using?
      placeholder: 3.0.0 (Build XXXXX)
    validations:
      required: true

  - type: input
    id: windows
    attributes:
      label: Windows Version
      placeholder: Windows 11 23H2
    validations:
      required: true

  - type: input
    id: model
    attributes:
      label: Laptop Model
      placeholder: LOQ 15IRX9
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Describe what is happening.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Open app
        2. Change performance mode
        3. Observe lag
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs (if available)
      description: Attach logs from AppData if possible.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I am using the latest release.
          required: true
        - label: I have checked existing issues.
          required: true
